// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qctjxwpuyhwiulyryjrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjdGp4d3B1eWh3aXVseXJ5anJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NjkyMTUsImV4cCI6MjA3MTI0NTIxNX0.zTMKB7uILGOOLh2riRIGaicMwIlNA2V1kg1U8mpSY3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});